name = "Experiments"
uuid = "41513fc1-ecef-46b8-a434-33d6e6fb829e"
authors = ["Fabian Müller"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
